game_words = [
    ["guitar", "a musical instrument"],
    ["piano", "a musical instrument"],
    ["violin", "a musical instrument"],
    ["drum", "a musical instrument"],
    ["flute", "a musical instrument"],
    ["pen", "a writing tool"],
    ["pencil", "a writing tool"],
    ["ruler", "a writing tool"],
    ["marker", "a writing tool"],
    ["mouse", "an input device"],
    ["keyboard", "an input device"],
    ["monitor", "an output device"],
    ["hat", "a headgear"],
    ["shoes", "footwear"],
    ["socks", "footwear"],
    ["jacket", "a cloth"],
    ["sweatshirt", "a cloth"],
    ["skirt", "a cloth"],
    ["dress", "a cloth"],
    ["pants", "cloth"],
    ["apple", "a fruit"],
    ["banana", "a fruit"],
    ["orange", "a fruit"],
    ["pear", "a fruit"],
    ["cat", "an animal"],
    ["dog", "an animal"],
    ["bird", "an animal"],
    ["fish", "an animal"],
    ["horse", "an animal"],
    ["cow", "an animal"],
    ["python", "programming language"],
    ["java", "programming language"],
    ["javascript", "programming language"],
    ["php", "programming language"]
];
